package life.sekejap.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import java.io.OutputStreamWriter

private const val PKG = "life.sekejap"

class SekejapProcessorProvider : SymbolProcessorProvider {
    override fun create(env: SymbolProcessorEnvironment) =
        SekejapProcessor(env.codeGenerator, env.logger)
}

class SekejapProcessor(
    private val gen: CodeGenerator,
    private val log: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation("$PKG.SekejapEntity")
            .filterIsInstance<KSClassDeclaration>()
        for (cls in symbols) generate(cls)
        return emptyList()
    }

    private fun generate(cls: KSClassDeclaration) {
        val className = cls.simpleName.asString()
        val lower = className.replaceFirstChar { it.lowercase() }
        val collection = annArg(cls.annotations, "SekejapEntity", "collection")
            ?.takeIf { it.isNotEmpty() } ?: pluralize(className.lowercase())

        val fields = cls.getAllProperties().mapNotNull { toField(it) }.toList()
        val key = fields.firstOrNull { it.isKey }
        if (key == null) {
            log.error("@SekejapEntity `$className` needs exactly one @Key property.", cls)
            return
        }

        val createCols = fields.joinToString(", ") {
            if (it.isKey) "${it.column} ${it.sqlType} PRIMARY KEY" else "${it.column} ${it.sqlType}"
        }
        val indexes = fields.mapNotNull { f ->
            f.indexUsing?.let { "\"CREATE INDEX ON $collection USING $it (${f.column})\"" }
        }
        val indexList = if (indexes.isEmpty()) "emptyList()" else "listOf(${indexes.joinToString(", ")})"

        val cols = fields.joinToString("\n") {
            "    val ${it.name} = Col<${it.colType}>(\"${it.column}\")"
        }
        val fromJson = fields.joinToString(",\n") { "        ${it.name} = ${it.fromJson()}" }
        val toJson = buildToJson(collection, fields)

        val targetPkg = cls.packageName.asString()
        val out = StringBuilder()
        out.append("// GENERATED by sekejap KSP — do not edit.\n")
        out.append("package $targetPkg\n\n")
        // Runtime types (skip when the entity is already in the runtime package,
        // to avoid redundant same-package imports).
        if (targetPkg != PKG) {
            for (t in listOf("Col", "Collection", "EntitySchema", "GeoPoint", "Sekejap", "VectorMetric")) {
                out.append("import $PKG.$t\n")
            }
        }
        out.append("import kotlinx.serialization.json.JsonArray\n")
        out.append("import kotlinx.serialization.json.JsonObject\n")
        out.append("import kotlinx.serialization.json.boolean\n")
        out.append("import kotlinx.serialization.json.double\n")
        out.append("import kotlinx.serialization.json.int\n")
        out.append("import kotlinx.serialization.json.jsonArray\n")
        out.append("import kotlinx.serialization.json.jsonObject\n")
        out.append("import kotlinx.serialization.json.jsonPrimitive\n")
        out.append("import kotlinx.serialization.json.long\n\n")

        out.append("val ${lower}Schema = EntitySchema(\n")
        out.append("    \"$collection\",\n")
        out.append("    \"CREATE TABLE $collection ($createCols)\",\n")
        out.append("    $indexList,\n)\n\n")

        out.append("class ${className}Columns {\n$cols\n}\n\n")

        // A single shared columns instance (the receiver is stateless), so
        // `db.$collection.where { … }` allocates no Columns object per call.
        out.append("private val ${lower}Columns = ${className}Columns()\n\n")

        out.append("class ${className}Collection(override val db: Sekejap) : Collection<$className, ${className}Columns>() {\n")
        out.append("    override val collectionName = \"$collection\"\n")
        out.append("    override val columns = ${lower}Columns\n")
        out.append("    override fun fromJson(payload: JsonObject): $className = $className(\n$fromJson,\n    )\n")
        out.append("    override fun toJson(entity: $className): String = $toJson\n")
        out.append("    override fun keyOf(entity: $className): String = entity.${key.name}\n")
        out.append("}\n\n")

        out.append("val Sekejap.$collection: ${className}Collection get() = ${className}Collection(this)\n")

        val file = gen.createNewFile(
            Dependencies(aggregating = false, cls.containingFile!!),
            targetPkg,
            "${className}_Sekejap",
        )
        OutputStreamWriter(file, Charsets.UTF_8).use { it.write(out.toString()) }
    }

    // ── field model ─────────────────────────────────────────────────────────────

    private fun toField(p: KSPropertyDeclaration): Field? {
        val type = p.type.resolve().declaration.simpleName.asString()
        val kind = when {
            hasAnn(p.annotations, "Geo") -> Kind.GEO
            hasAnn(p.annotations, "Vector") -> Kind.VECTOR
            hasAnn(p.annotations, "Bm25") -> Kind.BM25
            type == "String" -> Kind.TEXT
            type == "Int" -> Kind.INT
            type == "Long" -> Kind.LONG
            type == "Double" -> Kind.REAL
            type == "Float" -> Kind.REAL
            type == "Boolean" -> Kind.BOOL
            else -> Kind.JSON
        }
        val isKey = hasAnn(p.annotations, "Key")
        val idxAnn = p.annotations.firstOrNull { it.shortName.asString() == "Index" }
        val scalarIndex = idxAnn?.let {
            val k = argValue(it, "kind")?.toString() ?: ""
            if (k.contains("HASH")) "hash" else "btree"
        }
        val name = p.simpleName.asString()
        return Field(name, if (isKey) "_key" else name, type, kind, isKey, scalarIndex)
    }

    private fun hasAnn(anns: Sequence<KSAnnotation>, short: String) =
        anns.any { it.shortName.asString() == short }

    private fun annArg(anns: Sequence<KSAnnotation>, annShort: String, arg: String): String? =
        anns.firstOrNull { it.shortName.asString() == annShort }?.let { argValue(it, arg)?.toString() }

    private fun argValue(a: KSAnnotation, name: String): Any? =
        a.arguments.firstOrNull { it.name?.asString() == name }?.value

    private fun buildToJson(collection: String, fields: List<Field>): String {
        val sb = StringBuilder("buildString {\n")
        sb.append("        append(\"{\\\"_collection\\\":\\\"$collection\\\"\")\n")
        for (f in fields) {
            when (f.kind) {
                Kind.GEO -> sb.append("        append(\",\\\"${f.column}\\\":{\\\"type\\\":\\\"Point\\\",\\\"coordinates\\\":[\").append(entity.${f.name}.lon).append(\",\").append(entity.${f.name}.lat).append(\"]}\")\n")
                Kind.TEXT, Kind.BM25 -> sb.append("        append(\",\\\"${f.column}\\\":\\\"\").append(entity.${f.name}).append(\"\\\"\")\n")
                Kind.VECTOR -> sb.append("        append(\",\\\"${f.column}\\\":[\").append(entity.${f.name}.joinToString(\",\")).append(\"]\")\n")
                else -> sb.append("        append(\",\\\"${f.column}\\\":\").append(entity.${f.name})\n")
            }
        }
        sb.append("        append(\"}\")\n    }")
        return sb.toString()
    }
}

private enum class Kind { TEXT, INT, LONG, REAL, BOOL, GEO, VECTOR, BM25, JSON }

private class Field(
    val name: String,
    val column: String,
    val dartType: String,
    val kind: Kind,
    val isKey: Boolean,
    val scalarIndex: String?,
) {
    val sqlType: String get() = when (kind) {
        Kind.INT -> "INTEGER"; Kind.LONG -> "INTEGER"; Kind.REAL -> "REAL"
        Kind.BOOL -> "BOOLEAN"; Kind.GEO -> "GEO"; Kind.VECTOR -> "VECTOR"
        Kind.TEXT, Kind.BM25 -> "TEXT"; Kind.JSON -> "JSON"
    }
    val colType: String get() = when (kind) {
        Kind.GEO -> "GeoPoint"; Kind.VECTOR -> "List<Double>"; else -> dartType
    }
    val indexUsing: String? get() = when {
        isKey -> null
        kind == Kind.GEO -> "spatial"
        kind == Kind.VECTOR -> "hnsw"
        kind == Kind.BM25 -> "bm25"
        else -> scalarIndex
    }
    fun fromJson(): String {
        val k = "payload[\"$column\"]!!"
        return when (kind) {
            Kind.TEXT, Kind.BM25 -> "$k.jsonPrimitive.content"
            Kind.INT -> "$k.jsonPrimitive.int"
            Kind.LONG -> "$k.jsonPrimitive.long"
            Kind.REAL -> "$k.jsonPrimitive.double"
            Kind.BOOL -> "$k.jsonPrimitive.boolean"
            Kind.VECTOR -> "(payload[\"$column\"]?.jsonArray ?: JsonArray(emptyList())).map { it.jsonPrimitive.double }"
            Kind.GEO -> "GeoPoint(($k.jsonObject[\"coordinates\"]!!.jsonArray[0]).jsonPrimitive.double, ($k.jsonObject[\"coordinates\"]!!.jsonArray[1]).jsonPrimitive.double)"
            Kind.JSON -> "$k.jsonPrimitive.content"
        }
    }
}

private fun pluralize(w: String): String = when {
    w.endsWith("s") || w.endsWith("x") || w.endsWith("z") ||
        w.endsWith("ch") || w.endsWith("sh") -> "${w}es"
    w.endsWith("y") && w.length > 1 && w[w.length - 2] !in "aeiou" ->
        "${w.dropLast(1)}ies"
    else -> "${w}s"
}
