builders:
  sekejap:
    import: "package:sekejap_generator/sekejap_generator.dart"
    builder_factories: ["sekejapBuilder"]
    build_extensions: { ".dart": [".sekejap.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
