<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <!-- keep Debug.Assert active in this demo -->
    <DefineConstants>DEBUG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sekejap\Sekejap.csproj" />
  </ItemGroup>

</Project>
