// A sample entity the developer writes by hand. `dish.g.dart` is generated by
// `dart run build_runner build` (hand-written here to pin the codegen target).
import 'package:sekejap/sekejap.dart';

part 'dish.g.dart';

@SekejapEntity()
class Dish {
  @Key()
  final String id;
  @Index()
  final String category;
  final int price;
  final bool openNow;

  const Dish({
    required this.id,
    required this.category,
    required this.price,
    required this.openNow,
  });
}
