/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** The library version. */
export declare function version(): string
/**
 * An open sekejap database. JS is single-threaded, but we guard with a Mutex so
 * the handle is sound even if shared via worker threads.
 */
export declare class Db {
  /** Open (or create) a database at `path`. */
  static open(path: string): Db
  /** Run a mutating statement; returns affected rows. */
  execute(sql: string): number
  /** Run a SELECT; returns a JSON-array string (caller `JSON.parse`s it). */
  query(sql: string): string
  /** Parameterized SELECT ($1, $2, …); `paramsJson` is a JSON array string. */
  queryParams(sql: string, paramsJson: string): string
  /** Compile a query once for repeated execution — a prepared statement. */
  prepare(sql: string): PreparedStatement
  /**
   * Run a prepared statement, binding `$1`, `$2`, … from a JSON-array string.
   * Returns a JSON-array string (caller `JSON.parse`s it).
   */
  queryPrepared(stmt: PreparedStatement, paramsJson: string): string
  /** Insert/replace one node by slug with a JSON payload. */
  put(slug: string, payloadJson: string): void
  /** Create a plain edge from -> to of the given type. */
  link(from: string, to: string, edgeType: string): void
  /** Number of nodes. */
  nodeCount(): number
  /** Number of edges. */
  edgeCount(): number
  /** Compact: truncate WAL, rewrite payloads/topology, reclaim RAM. */
  compact(): void
}
/** A prepared (compiled) query — from `Db.prepare`, run with `Db.queryPrepared`. */
export declare class PreparedStatement { }
