/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** The library version. */
export declare function version(): string
/**
 * An open sekejap database. JS is single-threaded, but we guard with a Mutex so
 * the handle is sound even if shared via worker threads.
 */
export declare class Db {
  /** Open (or create) a database at `path`. */
  static open(path: string): Db
  /** Run a mutating statement; returns affected rows. */
  execute(sql: string): number
  /** Run a SELECT; returns a JSON-array string (caller `JSON.parse`s it). */
  query(sql: string): string
  /** Parameterized SELECT ($1, $2, …); `paramsJson` is a JSON array string. */
  queryParams(sql: string, paramsJson: string): string
  /**
   * Parameterized mutating statement ($1, $2, …); `paramsJson` is a JSON array
   * string. Returns affected rows. The typed layer's update/delete lower here.
   */
  executeParams(sql: string, paramsJson: string): number
  /**
   * Subscribe to the change feed. `callback` is invoked once per committed
   * mutation (a transaction fires once, at COMMIT) with a JSON string
   * `{"collections":[…],"keys":[…],"edge_types":[…]}`. Returns a subscription
   * id; pass it to [`unwatch`] to stop. The napi ThreadsafeFunction marshals
   * the call onto the JS event loop, so no manual threading is needed.
   */
  watch(callback: (arg: string) => any): number
  /** Stop a change-feed subscription created by [`watch`]. */
  unwatch(id: number): void
  /** Compile a query once for repeated execution — a prepared statement. */
  prepare(sql: string): PreparedStatement
  /**
   * Run a prepared statement, binding `$1`, `$2`, … from a JSON-array string.
   * Returns a JSON-array string (caller `JSON.parse`s it).
   */
  queryPrepared(stmt: PreparedStatement, paramsJson: string): string
  /** Insert/replace one node by slug with a JSON payload. */
  put(slug: string, payloadJson: string): void
  /** Create a plain edge from -> to of the given type. */
  link(from: string, to: string, edgeType: string): void
  /** Number of nodes. */
  nodeCount(): number
  /** Number of edges. */
  edgeCount(): number
  /** Compact: truncate WAL, rewrite payloads/topology, reclaim RAM. */
  compact(): void
  /**
   * Open an existing database in paged mode: identity/topology served from
   * memory-mapped files — small open time and resident memory at any size.
   */
  static openPaged(path: string): Db
  /** Open an existing database read-only. */
  static openReadOnly(path: string): Db
  /** A node's raw JSON payload, or null. */
  get(slug: string): string | null
  /** True if the node exists. */
  contains(slug: string): boolean
  /** Delete a node (and its edges). */
  remove(slug: string): void
  /**
   * Store many nodes in one batch (single disk sync).
   * `pairsJson` is a JSON array of `[slug, payloadJson]` pairs.
   */
  putMany(pairsJson: string): number
  /** Begin a bulk-load scope (defer the per-write disk sync). Pair with `endBulk`. */
  beginBulk(): void
  /** End a bulk-load scope: one disk sync for the whole batch. */
  endBulk(): void
  /** Store an embedding under a named field of a node. */
  putVector(slug: string, field: string, data: Array<number>): void
  /** The stored embedding for a node's field, or null. */
  getVector(slug: string, field: string): Array<number> | null
  /** Create an edge with JSON attributes (primitives ride fast columns). */
  linkMeta(from: string, to: string, edgeType: string, metaJson: string): void
  /**
   * Create many edges in one batch (single disk sync).
   * `edgesJson` is a JSON array of `[from, to, edgeType]` triples.
   */
  linkMany(edgesJson: string): void
  /** Remove a directed edge. */
  unlink(from: string, to: string, edgeType: string): void
  /**
   * Remove edges matching attribute equality conditions (`propsJson` is a
   * JSON object). Returns how many were removed.
   */
  unlinkWhere(from: string, to: string, edgeType: string, propsJson: string): number
  /**
   * Update attributes on matching edges: `propsJson` selects, `setsJson`
   * assigns. Returns how many were updated.
   */
  updateEdge(from: string, to: string, edgeType: string, propsJson: string, setsJson: string): number
  /**
   * Edges leaving a node, as a JSON-array string of
   * `{from, to, type, meta}` objects.
   */
  edgesFrom(slug: string): string
  /** Edges arriving at a node, same shape as `edgesFrom`. */
  edgesTo(slug: string): string
  /** Edges from one collection to another, same shape as `edgesFrom`. */
  edgesBetween(fromCollection: string, toCollection: string): string
  /** All collection names. */
  collectionNames(): Array<string>
  /** Every node slug. */
  allSlugs(): Array<string>
  /** DDL string for a collection schema, or null. */
  schemaDdl(collection: string): string | null
  /**
   * Ranked text search over a BM25-indexed field: JSON-array string of
   * `[slug, score]` pairs, best first.
   */
  bm25Search(field: string, query: string, topK: number): string
  /**
   * The query plan for a statement, as a JSON-array string (one step per
   * element). `analyze = true` also executes it and adds per-step timings.
   */
  explain(sql: string, analyze?: boolean | undefined | null): string
  /** Run a SHOW statement (`SHOW TABLES`, `SHOW EDGES`, …); JSON-array string. */
  show(sql: string): string
  /** Shrink resident memory to the live working set (never drops indexes). */
  trimMemory(): void
  /** Per-structure resident-memory estimate, as a JSON object string. */
  memoryReport(): string
  /** Override HNSW search breadth (`efSearch`); null restores the default. */
  setHnswEfSearch(ef?: number | undefined | null): void
  /**
   * Close the database and release its lock. Further calls error (or no-op
   * for count/list getters). Safe to call twice.
   */
  close(): void
}
/** A prepared (compiled) query — from `Db.prepare`, run with `Db.queryPrepared`. */
export declare class PreparedStatement { }
