// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Open a persistent database at `path` (a directory on the filesystem).
Future<SekejapDb> dbOpen({required String path}) =>
    RustLib.instance.api.crateApiSimpleDbOpen(path: path);

/// Create an in-memory (non-persistent) database.
Future<SekejapDb> dbNew() => RustLib.instance.api.crateApiSimpleDbNew();

/// Run a DDL/DML statement (CREATE, INSERT, UPDATE, DELETE).
/// Returns the number of rows affected.
Future<BigInt> dbExecute({required SekejapDb db, required String sql}) =>
    RustLib.instance.api.crateApiSimpleDbExecute(db: db, sql: sql);

/// Store a node. `json` must be a valid JSON object containing `_collection`.
/// Returns the internal storage id of the written node.
Future<BigInt> dbPut({
  required SekejapDb db,
  required String slug,
  required String json,
}) => RustLib.instance.api.crateApiSimpleDbPut(db: db, slug: slug, json: json);

/// Remove a node (and its associated edges).
Future<void> dbRemove({required SekejapDb db, required String slug}) =>
    RustLib.instance.api.crateApiSimpleDbRemove(db: db, slug: slug);

/// Create a directed edge: `from -[edge_type]-> to`.
Future<void> dbLink({
  required SekejapDb db,
  required String from,
  required String to,
  required String edgeType,
}) => RustLib.instance.api.crateApiSimpleDbLink(
  db: db,
  from: from,
  to: to,
  edgeType: edgeType,
);

/// Remove a directed edge between two nodes.
Future<void> dbUnlink({
  required SekejapDb db,
  required String from,
  required String to,
  required String edgeType,
}) => RustLib.instance.api.crateApiSimpleDbUnlink(
  db: db,
  from: from,
  to: to,
  edgeType: edgeType,
);

/// Run a SELECT or MATCH query.
/// Returns a JSON array: `[{"slug":"...","payload":{...}}, ...]`
Future<String> dbQuery({required SekejapDb db, required String sql}) =>
    RustLib.instance.api.crateApiSimpleDbQuery(db: db, sql: sql);

/// Run a SELECT or MATCH query with parameter bindings ($1, $2, …).
/// `params_json` is a JSON array of values, e.g. `'["Alice", 25]'`.
/// Returns a JSON array: `[{"slug":"...","payload":{...}}, ...]`
Future<String> dbQueryParams({
  required SekejapDb db,
  required String sql,
  required String paramsJson,
}) => RustLib.instance.api.crateApiSimpleDbQueryParams(
  db: db,
  sql: sql,
  paramsJson: paramsJson,
);

/// Compile a query once for repeated execution (a prepared statement). Use
/// `$1`, `$2`, … placeholders and bind them per run via [`db_query_prepared`].
Future<SekejapPreparedQuery> dbPrepare({
  required SekejapDb db,
  required String sql,
}) => RustLib.instance.api.crateApiSimpleDbPrepare(db: db, sql: sql);

/// Run a prepared statement, binding $1, $2, … from `params_json` (a JSON array).
/// Returns a JSON array: `[{"slug":"...","payload":{...}}, ...]`
Future<String> dbQueryPrepared({
  required SekejapDb db,
  required SekejapPreparedQuery stmt,
  required String paramsJson,
}) => RustLib.instance.api.crateApiSimpleDbQueryPrepared(
  db: db,
  stmt: stmt,
  paramsJson: paramsJson,
);

/// Run a DDL/DML statement with parameter bindings ($1, $2, …).
/// `params_json` is a JSON array of values.
/// Returns the number of rows affected.
Future<BigInt> dbExecuteParams({
  required SekejapDb db,
  required String sql,
  required String paramsJson,
}) => RustLib.instance.api.crateApiSimpleDbExecuteParams(
  db: db,
  sql: sql,
  paramsJson: paramsJson,
);

/// Get a single node by slug. Returns its JSON payload string, or null.
Future<String?> dbGet({required SekejapDb db, required String slug}) =>
    RustLib.instance.api.crateApiSimpleDbGet(db: db, slug: slug);

/// Check whether a node with the given slug exists.
Future<bool> dbContains({required SekejapDb db, required String slug}) =>
    RustLib.instance.api.crateApiSimpleDbContains(db: db, slug: slug);

/// Run a SHOW statement. Returns a JSON array.
Future<String> dbShow({required SekejapDb db, required String sql}) =>
    RustLib.instance.api.crateApiSimpleDbShow(db: db, sql: sql);

/// Flush WAL and write a full snapshot.
Future<void> dbCompact({required SekejapDb db}) =>
    RustLib.instance.api.crateApiSimpleDbCompact(db: db);

/// Flush WAL to disk without full compaction.
Future<void> dbSync({required SekejapDb db}) =>
    RustLib.instance.api.crateApiSimpleDbSync(db: db);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SekejapDb>>
abstract class SekejapDb implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SekejapPreparedQuery>>
abstract class SekejapPreparedQuery implements RustOpaqueInterface {}
