#!/usr/bin/env bash
#
# Generate a code outline of the repo: the file tree, and under each file its
# types (struct/enum/trait) and functions with line numbers — so you can jump
# straight to `file:line` instead of grepping.
#
#   scripts/repo-outline.sh              # write docs/developer/repo-outline.md
#   scripts/repo-outline.sh --stdout     # print instead of writing
#   scripts/repo-outline.sh --all        # include private fns too (default: types
#                                        #   + pub fns + impl blocks)
#   scripts/repo-outline.sh --check      # exit 1 if the committed file is stale
#
# Regenerate it whenever the code structure changes (see scripts/pre-commit.sh,
# which runs this and stages the result).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OUT="docs/developer/repo-outline.md"

MODE_STDOUT=0; MODE_CHECK=0; INCLUDE_ALL=0
for a in "$@"; do
  case "$a" in
    --stdout) MODE_STDOUT=1 ;;
    --check)  MODE_CHECK=1 ;;
    --all)    INCLUDE_ALL=1 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown option: $a" >&2; exit 2 ;;
  esac
done

GENERATED=$(INCLUDE_ALL="$INCLUDE_ALL" python3 - <<'PY'
import os, re, sys

include_all = os.environ.get("INCLUDE_ALL") == "1"
ROOTS = ["src", "skcli/src"]
MAXSIG = 96

def rust_files():
    out = []
    for root in ROOTS:
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = sorted(d for d in dirnames if d != "target")
            for fn in sorted(filenames):
                if fn.endswith(".rs"):
                    out.append(os.path.join(dirpath, fn))
    return sorted(out)

def module_doc(lines):
    """The file's own `//! # Title` (or first //! line) — its purpose."""
    first = None
    for ln in lines[:40]:
        s = ln.strip()
        if s.startswith("//!"):
            body = s[3:].strip()
            if body and first is None:
                first = body
            m = re.match(r"#\s+(.*)", body)
            if m:
                return m.group(1).strip()
    return first or ""

# Top-level-ish item patterns. `indent` decides nesting (rustfmt keeps this sane).
ITEM = re.compile(
    r"""^(?P<indent>\s*)
        (?P<vis>pub(\([^)]*\))?\s+)?
        (?P<kind>struct|enum|trait|union|impl|fn|macro_rules!|type|mod)
        \s+(?P<rest>.*)$""",
    re.X,
)

def clean(sig):
    sig = sig.rstrip()
    for tail in (" {", "{"):
        if sig.endswith(tail):
            sig = sig[: -len(tail)].rstrip()
    sig = sig.rstrip(";").rstrip()
    sig = re.sub(r"\s+", " ", sig)
    if len(sig) > MAXSIG:
        sig = sig[: MAXSIG - 1] + "…"
    return sig

def outline(path):
    text = open(path, encoding="utf-8", errors="replace").read()
    lines = text.splitlines()
    items = []
    in_block_comment = False
    for i, raw in enumerate(lines, 1):
        s = raw.strip()
        # skip comments / doc comments / attributes / strings-ish noise
        if in_block_comment:
            if "*/" in s:
                in_block_comment = False
            continue
        if s.startswith("/*"):
            if "*/" not in s:
                in_block_comment = True
            continue
        if s.startswith(("//", "#[", "#!")) or not s:
            continue
        m = ITEM.match(raw)
        if not m:
            continue
        kind = m.group("kind")
        vis = (m.group("vis") or "").strip()
        indent = len(m.group("indent"))
        rest = m.group("rest")
        # `mod` only when it opens an inline module (not `mod x;` or `use`)
        if kind == "mod" and not rest.rstrip().endswith("{"):
            continue
        if kind == "type" and indent > 0 and not vis:
            continue  # associated type noise
        is_pub = vis.startswith("pub")
        if kind == "fn" and not include_all and not is_pub and indent > 0:
            # keep private top-level fns (indent 0) — they're often the real logic
            continue
        name_sig = clean(("%s %s %s" % (vis, kind, rest)).strip())
        items.append((i, indent, kind, name_sig))
    return lines, items

files = rust_files()
print("# Repo outline — types & functions, with line numbers")
print()
print("Generated by `scripts/repo-outline.sh` — **do not edit by hand.**")
print("Every entry is `line  item`, so you can jump straight to `file:line`.")
print(f"Scope: `{'`, `'.join(ROOTS)}`." + ("" if include_all else
      " Shows types, `impl` blocks, public functions, and top-level private functions"
      " (run with `--all` to include every private function)."))
print()
total_items = 0
cur_dir = None
for path in files:
    lines, items = outline(path)
    total_items += len(items)
    d = os.path.dirname(path)
    if d != cur_dir:
        cur_dir = d
        print(f"## `{d}/`")
        print()
    doc = module_doc(lines)
    head = f"### `{os.path.basename(path)}` · {len(lines)}L"
    if doc:
        head += f" — {doc}"
    print(head)
    print()
    if not items:
        print("```")
        print("(no top-level items)")
        print("```")
        print()
        continue
    print("```")
    for ln, indent, kind, sig in items:
        pad = "  " * min(indent // 4, 3)
        print(f"{ln:>6}  {pad}{sig}")
    print("```")
    print()
print(f"<!-- {len(files)} files, {total_items} items -->")
PY
)

if [ "$MODE_STDOUT" = "1" ]; then
  printf '%s\n' "$GENERATED"
  exit 0
fi

if [ "$MODE_CHECK" = "1" ]; then
  if [ ! -f "$OUT" ] || ! printf '%s\n' "$GENERATED" | diff -q - "$OUT" >/dev/null 2>&1; then
    echo "repo outline is stale — run scripts/repo-outline.sh" >&2
    exit 1
  fi
  echo "repo outline is up to date"
  exit 0
fi

mkdir -p "$(dirname "$OUT")"
printf '%s\n' "$GENERATED" > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines, $(du -h "$OUT" | cut -f1))"
