//! One-time analyzer table snapshot, NOT a build script.
//! Compile with the recorded Rust toolchain and redirect into a NEW candidate.
//! Never regenerate a released analyzer's tables in place.
fn main() {
    println!("// Generated by tools/generate_text_unicode_v1.rs; not regenerated at build time.");
    println!("// Unicode property/case results from the recorded Rust standard library.");
    println!("// Source: https://doc.rust-lang.org/std/primitive.char.html");
    println!(
        "pub const UNICODE_VERSION: (u8, u8, u8) = {:?};",
        std::char::UNICODE_VERSION
    );
    println!(
        "pub const GENERATOR_COMPILER: &str = {:?};",
        option_env!("E4_UNICODE_GENERATOR_COMPILER").unwrap_or("unrecorded")
    );
    let mut ranges = Vec::<(u32, u32)>::new();
    let mut lower = Vec::new();
    for cp in 0..=0x10ffff {
        let Some(c) = char::from_u32(cp) else {
            continue;
        };
        if c.is_alphanumeric() {
            if let Some(last) = ranges.last_mut().filter(|r| r.1 + 1 == cp) {
                last.1 = cp;
            } else {
                ranges.push((cp, cp));
            }
        }
        let folded: String = c.to_lowercase().collect();
        if folded != c.to_string() {
            lower.push((cp, folded));
        }
    }
    println!("pub static ALNUM: &[(u32, u32)] = &[");
    for (a, b) in ranges {
        println!("    (0x{a:x}, 0x{b:x}),");
    }
    println!("];");
    println!("pub static LOWER: &[(u32, &str)] = &[");
    for (cp, value) in lower {
        println!("    (0x{cp:x}, {value:?}),");
    }
    println!("];");
}
