//! The geometry I/O functions against PostGIS: WKB and EWKB in both byte
//! orders, WKT, GeoJSON text, and the `&&` bounding-box test.
//!
//! Oracle: `tests/fixtures/postgis_wkb.json`, generated by
//! `tools/postgis_wkb_fixture.py` (seed 20260925) with one batched `SELECT`
//! against live PostGIS 3.4. This file is offline: it never talks to
//! Postgres. Every case is parsed from the WKT PostGIS was given, written back
//! in every format, and compared byte for byte with what PostGIS printed; then
//! each of PostGIS's byte strings is read back and must give the same shape.

use kernel::spatial::Geom;
use sekejap_core::spatial_geometry::bbox_overlaps;
use sekejap_core::spatial_io::{
    from_hex, from_wkb, from_wkt, to_ewkb, to_geojson, to_hex, to_wkb, to_wkt, ByteOrder,
};
use serde_json::Value;

fn fixture() -> Value {
    let raw = std::fs::read_to_string("tests/fixtures/postgis_wkb.json")
        .expect("tests/fixtures/postgis_wkb.json -- run tools/postgis_wkb_fixture.py");
    serde_json::from_str(&raw).expect("fixture must be valid JSON")
}

fn cases() -> Vec<Value> {
    fixture()["cases"].as_array().expect("cases").clone()
}

fn text(case: &Value, key: &str) -> String {
    case[key].as_str().unwrap_or_else(|| panic!("{key} missing")).to_owned()
}

#[test]
fn every_shape_writes_the_bytes_postgis_writes_in_both_byte_orders() {
    let cases = cases();
    assert!(cases.len() >= 30, "the fixture holds the six shapes and their random cases");
    for case in &cases {
        let wkt = text(case, "wkt");
        let shape = from_wkt(&wkt).unwrap_or_else(|e| panic!("{wkt}: {e}")).geometry;
        assert_eq!(to_hex(&to_wkb(&shape, ByteOrder::Little)), text(case, "wkb_ndr"), "{wkt} NDR");
        assert_eq!(to_hex(&to_wkb(&shape, ByteOrder::Big)), text(case, "wkb_xdr"), "{wkt} XDR");
        assert_eq!(
            to_hex(&to_ewkb(&shape, Some(4326), ByteOrder::Little)),
            text(case, "ewkb_ndr"),
            "{wkt} EWKB NDR"
        );
        assert_eq!(
            to_hex(&to_ewkb(&shape, Some(4326), ByteOrder::Big)),
            text(case, "ewkb_xdr"),
            "{wkt} EWKB XDR"
        );
    }
}

#[test]
fn every_byte_string_postgis_wrote_reads_back_as_the_same_shape() {
    for case in cases() {
        let wkt = text(&case, "wkt");
        let shape = from_wkt(&wkt).unwrap().geometry;
        for (key, srid) in [
            ("wkb_ndr", None),
            ("wkb_xdr", None),
            ("ewkb_ndr", Some(4326)),
            ("ewkb_xdr", Some(4326)),
        ] {
            let bytes = from_hex(&text(&case, key)).unwrap();
            let read = from_wkb(&bytes).unwrap_or_else(|e| panic!("{wkt} {key}: {e}"));
            assert_eq!(read.geometry, shape, "{wkt} {key}");
            assert_eq!(read.srid, srid, "{wkt} {key}");
        }
    }
}

#[test]
fn text_and_geojson_print_what_postgis_prints() {
    for case in cases() {
        let wkt = text(&case, "wkt");
        let shape = from_wkt(&wkt).unwrap().geometry;
        assert_eq!(to_wkt(&shape), text(&case, "text"), "ST_AsText({wkt})");
        assert_eq!(to_geojson(&shape, 9), text(&case, "geojson"), "ST_AsGeoJSON({wkt})");
        // What ST_AsText printed must read back to a shape that prints the
        // same again: the text form is a fixed point.
        let again = from_wkt(&text(&case, "text")).unwrap().geometry;
        assert_eq!(to_wkt(&again), text(&case, "text"), "{wkt} round trip");
    }
}

#[test]
fn st_x_and_st_y_are_the_point_coordinates_postgis_reports() {
    for case in cases() {
        let Some(x) = case["x"].as_f64() else { continue };
        let y = case["y"].as_f64().unwrap();
        let wkt = text(&case, "wkt");
        match from_wkt(&wkt).unwrap().geometry {
            Geom::Point(px, py) => {
                assert_eq!(px, x, "ST_X({wkt})");
                assert_eq!(py, y, "ST_Y({wkt})");
            }
            other => panic!("{wkt} read as {other:?}"),
        }
    }
}

/// `&&` compares float4 boxes rounded OUTWARD, so a point one ten-billionth
/// of a degree past an edge still overlaps. The fixture holds that case and
/// the double-precision test would get it wrong.
#[test]
fn bbox_overlap_answers_what_postgis_answers_for_every_pair() {
    let fixture = fixture();
    let pairs = fixture["overlaps"].as_array().unwrap();
    assert!(pairs.iter().any(|p| p["overlaps"].as_bool() == Some(true)));
    assert!(pairs.iter().any(|p| p["overlaps"].as_bool() == Some(false)));
    for pair in pairs {
        let a = from_wkt(pair["a"].as_str().unwrap()).unwrap().geometry;
        let b = from_wkt(pair["b"].as_str().unwrap()).unwrap().geometry;
        let want = pair["overlaps"].as_bool().unwrap();
        assert_eq!(bbox_overlaps(&a, &b), want, "{} && {}", pair["a"], pair["b"]);
        assert_eq!(bbox_overlaps(&b, &a), want, "&& is symmetric");
    }
}

// ── what is refused, and that a refusal never panics ─────────────────────

#[test]
fn a_truncated_byte_string_is_an_error_at_every_length() {
    for case in cases() {
        let bytes = from_hex(&text(&case, "ewkb_xdr")).unwrap();
        for cut in 0..bytes.len() {
            assert!(from_wkb(&bytes[..cut]).is_err(), "{} cut at {cut}", text(&case, "wkt"));
        }
    }
}

#[test]
fn trailing_bytes_after_a_geometry_are_refused() {
    let mut bytes = from_hex("0101000000000000000000f03f0000000000000040").unwrap();
    bytes.push(0);
    assert!(from_wkb(&bytes).is_err());
}

/// A count that claims more elements than the bytes can hold is refused
/// BEFORE anything is allocated for it.
#[test]
fn a_count_larger_than_the_input_is_refused_without_allocating_it() {
    // LINESTRING claiming u32::MAX points, followed by one point.
    let bytes = from_hex("0102000000ffffffff000000000000f03f0000000000000040").unwrap();
    let error = from_wkb(&bytes).unwrap_err().to_string();
    assert!(error.contains("count"), "{error}");
    // MULTIPOLYGON claiming u32::MAX polygons.
    let bytes = from_hex("0106000000ffffffff").unwrap();
    assert!(from_wkb(&bytes).is_err());
}

#[test]
fn z_m_empty_and_collections_are_refused_by_name() {
    let refused = [
        // ISO WKB POINT Z (1001) and EWKB POINT with the Z flag.
        "01e9030000000000000000f03f00000000000000400000000000000840",
        "0101000080000000000000f03f00000000000000400000000000000840",
        // EWKB POINT with the M flag.
        "0101000040000000000000f03f00000000000000400000000000000840",
        // GEOMETRYCOLLECTION with no members.
        "010700000000000000",
        // LINESTRING EMPTY.
        "010200000000000000",
        // POINT EMPTY, which PostGIS writes as NaN NaN.
        "0101000000000000000000f87f000000000000f87f",
        // An unknown type.
        "0109000000",
        // A byte-order byte that is neither 0 nor 1.
        "0201000000000000000000f03f0000000000000040",
    ];
    for hex in refused {
        assert!(from_wkb(&from_hex(hex).unwrap()).is_err(), "{hex}");
    }
    for wkt in [
        "POINT Z (1 2 3)",
        "POINT M (1 2 3)",
        "POINT(1 2 3)",
        "POINT EMPTY",
        "GEOMETRYCOLLECTION(POINT(1 2))",
        "LINESTRING(1 2)",
        "POLYGON((0 0,1 0,1 1,0 0.5))",
        "POLYGON((0 0,1 1,0 0))",
        "POINT(1 2",
        "POINT(1 2) x",
        "POINT(NaN 2)",
    ] {
        assert!(from_wkt(wkt).is_err(), "{wkt}");
    }
}

/// A member of a multi-geometry must be the matching simple type, each with
/// its own byte-order byte.
#[test]
fn a_multipoint_holding_a_linestring_is_refused() {
    // MULTIPOINT with one member whose type is LINESTRING.
    let bytes = from_hex("01040000000100000001020000000100000000000000000000000000000000000000").unwrap();
    assert!(from_wkb(&bytes).is_err());
}

#[test]
fn mixed_byte_orders_inside_one_multi_geometry_read_correctly() {
    // MULTIPOINT(1 2,3 4): outer NDR, first member XDR, second NDR.
    let hex = concat!(
        "010400000002000000",
        "00000000013ff00000000000004000000000000000",
        "0101000000000000000000084000000000000010" , "40"
    );
    let read = from_wkb(&from_hex(hex).unwrap()).unwrap();
    assert_eq!(read.geometry, Geom::MultiPoint(vec![[1.0, 2.0], [3.0, 4.0]]));
}

#[test]
fn hex_is_read_with_or_without_the_bytea_prefix_and_in_either_case() {
    let plain = from_hex("0101000000000000000000F03F0000000000000040").unwrap();
    let prefixed = from_hex("\\x0101000000000000000000f03f0000000000000040").unwrap();
    assert_eq!(plain, prefixed);
    assert!(from_hex("0101z").is_err());
    assert!(from_hex("010").is_err());
}

#[test]
fn ewkt_carries_its_srid_and_plain_wkt_has_none() {
    let read = from_wkt("SRID=4326;POINT(1 2)").unwrap();
    assert_eq!(read.srid, Some(4326));
    assert_eq!(read.geometry, Geom::Point(1.0, 2.0));
    assert_eq!(from_wkt("point ( 1 2 )").unwrap().srid, None);
}

/// A ring stored without its closing point is written closed: WKB and WKT
/// both require it, and a reader that meets an open ring refuses the shape.
#[test]
fn an_implicitly_closed_ring_is_written_closed() {
    let open = Geom::Polygon(vec![vec![[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]]]);
    assert_eq!(to_wkt(&open), "POLYGON((0 0,1 0,1 1,0 1,0 0))");
    let read = from_wkb(&to_wkb(&open, ByteOrder::Little)).unwrap().geometry;
    assert_eq!(to_wkt(&read), "POLYGON((0 0,1 0,1 1,0 1,0 0))");
}
