//! Adversarial conformance of `src/spatial_geometry.rs` against PostGIS.
//!
//! Loop 2 (`geo2`) patched the engine for the five classes that were E4's
//! own: the constant-latitude edge midpoint, the antimeridian far-point
//! distance, the large-span geodesic interior, the polar triangle, and the
//! ±180 polar rectangle. Those repros now assert PostGIS's answer and pass.
//! The four classes E4 documents and does NOT copy stayed disagreements, and
//! are each a named `documented_*` test below plus one arm of
//! [`documented_deviation`], which the family walks route them through — so
//! a green family test says "nothing disagrees except these four", never
//! "nothing disagrees".
//!
//! Oracle: `tests/fixtures/postgis_conformance.json`, generated by
//! `tools/postgis_conformance_fixture.py` (seed 20260919) with one batched
//! `SELECT` per family against live PostGIS. This file is offline: it never
//! talks to Postgres. Failures are deliverables — the engine is not patched
//! here; each disagreement class is a named test plus a print of pair index,
//! both GeoJSONs, and both answers.

use sekejap_core::spatial_geometry::*;
use kernel::spatial::Geom;
use serde_json::Value;
use std::fmt::Write as _;

fn fixture() -> Value {
    let raw = std::fs::read_to_string("tests/fixtures/postgis_conformance.json")
        .expect("tests/fixtures/postgis_conformance.json — run tools/postgis_conformance_fixture.py");
    serde_json::from_str(&raw).expect("fixture must be valid JSON")
}

fn geom_from_geojson(v: &Value) -> Result<Geom, String> {
    let t = v["type"].as_str().ok_or_else(|| "missing geometry type".to_string())?;
    let c = v["coordinates"].clone();
    match t {
        "Point" => {
            let p: [f64; 2] = serde_json::from_value(c).map_err(|e| e.to_string())?;
            Ok(Geom::Point(p[0], p[1]))
        }
        "LineString" => Ok(Geom::LineString(serde_json::from_value(c).map_err(|e| e.to_string())?)),
        "Polygon" => Ok(Geom::Polygon(serde_json::from_value(c).map_err(|e| e.to_string())?)),
        "MultiPoint" => Ok(Geom::MultiPoint(serde_json::from_value(c).map_err(|e| e.to_string())?)),
        "MultiLineString" => {
            Ok(Geom::MultiLineString(serde_json::from_value(c).map_err(|e| e.to_string())?))
        }
        "MultiPolygon" => Ok(Geom::MultiPolygon(serde_json::from_value(c).map_err(|e| e.to_string())?)),
        other => Err(format!("unsupported geometry type {other}")),
    }
}

fn rel_or_abs(got: f64, want: f64, rel: f64, abs: f64) -> bool {
    if got.is_nan() && want.is_nan() {
        return true;
    }
    if !got.is_finite() || !want.is_finite() {
        return got.is_infinite() && want.is_infinite() && got.signum() == want.signum();
    }
    (got - want).abs() <= abs || ((got - want).abs() / want.abs().max(1e-12)) <= rel
}

/// Distances / lengths / perimeters: 1e-6 relative or 1 mm absolute
/// (`docs/core/SPATIAL_FUNCTIONS.md` owner spec).
fn dist_ok(got: f64, want: f64) -> bool {
    rel_or_abs(got, want, 1e-6, 1e-3)
}

/// Areas: 1e-6 relative, or 1e-3 m² absolute so a 0 vs 1e-9 pair does not fire.
fn area_ok(got: f64, want: f64) -> bool {
    rel_or_abs(got, want, 1e-6, 1e-3)
}

fn lonlat_gap_deg(got: (f64, f64), want: (f64, f64)) -> f64 {
    let mut dlon = (got.0 - want.0).abs();
    if dlon > 180.0 {
        dlon = 360.0 - dlon;
    }
    dlon.hypot((got.1 - want.1).abs())
}

/// Point/line centroids: 1e-6 deg (owner spec is 1e-9; float of the spherical
/// mean on fixture coordinates is ~1e-9..1e-7 in the existing PostGIS suite).
/// Areal centroids: 0.01 deg (~1.1 km). The documented hole-centroid gap is
/// 0.48 deg and is supposed to show up as a disagreement under this threshold.
fn centroid_tol(g: &Geom) -> f64 {
    match g {
        Geom::Polygon(_) | Geom::MultiPolygon(_) => 0.01,
        _ => 1e-6,
    }
}

struct Disagree {
    family: &'static str,
    i: usize,
    tag: String,
    pred: String,
    a: String,
    b: String,
    postgis: String,
    e4: String,
}

impl Disagree {
    fn dump(&self) -> String {
        format!(
            "DISAGREE {fam}[{i}] tag={tag} pred={pred}\n  a={a}\n  b={b}\n  postgis={pg}\n  e4={e4}",
            fam = self.family,
            i = self.i,
            tag = self.tag,
            pred = self.pred,
            a = self.a,
            b = self.b,
            pg = self.postgis,
            e4 = self.e4,
        )
    }
}

fn js(v: &Value) -> String {
    serde_json::to_string(v).unwrap_or_else(|_| "null".into())
}

fn empty_geom() -> Value {
    Value::Null
}

fn finish(family: &str, rows: &[Disagree]) {
    if rows.is_empty() {
        return;
    }
    let mut by = std::collections::BTreeMap::<String, usize>::new();
    for d in rows {
        *by.entry(format!("{} / {}", d.tag, d.pred)).or_insert(0) += 1;
    }
    let mut msg = String::new();
    let _ = writeln!(
        msg,
        "{family}: {} disagreements (pair index, GeoJSONs, both answers on stderr)",
        rows.len()
    );
    for (k, n) in &by {
        let _ = writeln!(msg, "  class {k}: {n}");
    }
    for d in rows.iter().take(8) {
        let _ = writeln!(msg, "{}", d.dump());
    }
    if rows.len() > 8 {
        let _ = writeln!(msg, "  ... {} more", rows.len() - 8);
    }
    for d in rows {
        eprintln!("{}", d.dump());
    }
    panic!("{msg}");
}

fn pair_geoms(pair: &Value) -> Result<(Geom, Geom), String> {
    let a = geom_from_geojson(&pair["a"])?;
    let b = geom_from_geojson(&pair["b"])?;
    Ok((a, b))
}

fn bool_field(v: &Value, k: &str) -> Option<bool> {
    v.get(k).and_then(Value::as_bool)
}

fn f64_field(v: &Value, k: &str) -> Option<f64> {
    v.get(k).and_then(Value::as_f64)
}

/// The widest gap this PostGIS geography snaps to a touch, in metres. The
/// observed case is 7.4 cm; a decimetre is the ceiling this file will call
/// "the documented snap" rather than a miss of a real intersection.
const PG_GEOGRAPHY_SNAP_M: f64 = 0.1;

/// Is this disagreement one of the four classes E4 documents and does not
/// copy? Returns the reason, which the walk prints instead of recording a
/// failure. Every arm is also a named `documented_*` test below, carrying
/// the PostGIS probe that establishes it.
fn documented_deviation(
    family: &str,
    tag: &str,
    pred: &str,
    a: &Geom,
    b: &Geom,
    pg: &Value,
) -> Option<&'static str> {
    match (family, tag, pred) {
        // C1: facing meridians ~7 cm apart. PostGIS geography reports a
        // touch and distance 0; Karney reports 0.074 m, which is the better
        // metre. Scoped to pairs PostGIS calls touching and E4 puts inside
        // the snap ceiling, so a real missed intersection still fails.
        ("a", "apart_0_3m", "intersects") | ("a", "apart_0_3m", "distance_m") => {
            let pg_touch = bool_field(pg, "intersects") == Some(true)
                && f64_field(pg, "distance_m").is_some_and(|d| d == 0.0);
            let gap = distance_m(a, b);
            (pg_touch && gap > 0.0 && gap <= PG_GEOGRAPHY_SNAP_M).then_some(
                "C1 PostGIS geography snaps a centimetre meridian gap to a touch; E4 keeps Karney's metre",
            )
        }
        // C4: rings are implicitly closed (`core/kernel/src/spatial.rs:348`).
        // PostGIS calls the open ring invalid and measures three sides.
        ("d", "unclosed_ring", _) => {
            Some("C4 E4 closes a ring implicitly; PostGIS refuses validity and measures it open")
        }
        // C5: GEOS answers Contains on a self-intersecting ring.
        ("d", "self_touching_ring", "contains") | ("d", "self_touching_ring", "within(point,a)") => {
            Some("C5 GEOS answers Contains on a bowtie; E4 does not copy invalid-input behaviour")
        }
        // C5, same class: a collapsed spike ring (`ST_IsValid` false,
        // self-intersection). PostGIS's polygon/boundary distance drops the
        // spike edge; asked for that same edge as a LINESTRING it returns
        // E4's own number. See `documented_collapsed_spike_ring_distance`.
        ("d", "zero_area", "distance_m") => {
            Some("C5 PostGIS drops one edge of a collapsed spike ring; E4 measures every edge")
        }
        // C9: planar area-weighted centroid, holes subtracted by position,
        // vs PostGIS's spherical one. Areal geometries only.
        ("h", _, "centroid") if matches!(a, Geom::Polygon(_) | Geom::MultiPolygon(_)) => {
            Some("C9 planar area-weighted areal centroid vs PostGIS's spherical one")
        }
        _ => None,
    }
}

fn check_pair_predicates(
    family: &'static str,
    pair: &Value,
    a: &Geom,
    b: &Geom,
    pg: &Value,
    rows: &mut Vec<Disagree>,
) {
    let i = pair["i"].as_u64().unwrap() as usize;
    let tag = pair["tag"].as_str().unwrap_or("").to_string();
    let ajs = js(&pair["a"]);
    let bjs = js(&pair["b"]);
    let mut push = |pred: &str, e4: String, postgis: String, ok: bool| {
        if ok {
            return;
        }
        if let Some(why) = documented_deviation(family, &tag, pred, a, b, pg) {
            eprintln!("DOCUMENTED {family}[{i}] tag={tag} pred={pred} e4={e4} postgis={postgis}: {why}");
            return;
        }
        rows.push(Disagree {
            family,
            i,
            tag: tag.clone(),
            pred: pred.to_string(),
            a: ajs.clone(),
            b: bjs.clone(),
            postgis,
            e4,
        });
    };

    if let Some(want) = bool_field(pg, "intersects") {
        let got = intersects(a, b);
        push("intersects", got.to_string(), want.to_string(), got == want);
    }
    if let Some(want) = bool_field(pg, "within") {
        let got = within(a, b);
        push("within", got.to_string(), want.to_string(), got == want);
    }
    if let Some(want) = bool_field(pg, "contains") {
        let got = contains(a, b);
        push("contains", got.to_string(), want.to_string(), got == want);
    }
    if let Some(want) = bool_field(pg, "dwithin_3m") {
        let got = dwithin_m(a, b, 3.0);
        push("dwithin_3m", got.to_string(), want.to_string(), got == want);
    }
    if let Some(want) = bool_field(pg, "dwithin_1km") {
        let got = dwithin_m(a, b, 1000.0);
        push("dwithin_1km", got.to_string(), want.to_string(), got == want);
    }
    if let Some(want) = f64_field(pg, "distance_m") {
        let got = distance_m(a, b);
        push(
            "distance_m",
            format!("{got}"),
            format!("{want}"),
            dist_ok(got, want),
        );
    }
}

fn load_pairs(fam: &str) -> Vec<Value> {
    fixture()["families"][fam]["pairs"]
        .as_array()
        .unwrap_or_else(|| panic!("{fam} pairs"))
        .clone()
}

fn load_singles(fam: &str) -> Vec<Value> {
    fixture()["families"][fam]["singles"]
        .as_array()
        .unwrap_or_else(|| panic!("{fam} singles"))
        .clone()
}

#[test]
fn fixture_records_postgis_version_and_sql_per_family() {
    let f = fixture();
    let v = f["postgis_version"].as_str().expect("postgis_version");
    assert!(v.contains("POSTGIS="), "version string: {v}");
    assert_eq!(f["seed"].as_u64(), Some(20260919));
    for name in [
        "a_nearby_polygons",
        "b_holes",
        "c_antimeridian_poles",
        "d_degenerate",
        "e_dwithin",
        "f_multi",
        "g_large_pole",
        "h_measures",
    ] {
        let sql = f["families"][name]["sql"].as_str().expect(name);
        assert!(sql.contains("ST_GeomFromGeoJSON"), "{name} sql missing ST_GeomFromGeoJSON");
        assert!(sql.contains("SELECT"), "{name} sql missing SELECT");
    }
}

#[test]
fn family_a_nearby_polygon_pairs() {
    let mut rows = Vec::new();
    for pair in load_pairs("a_nearby_polygons") {
        let (a, b) = pair_geoms(&pair).expect("geom");
        check_pair_predicates("a", &pair, &a, &b, &pair["postgis"], &mut rows);
    }
    finish("a_nearby_polygons", &rows);
}

#[test]
fn family_b_polygons_with_holes() {
    let mut rows = Vec::new();
    for pair in load_pairs("b_holes") {
        let (a, b) = pair_geoms(&pair).expect("geom");
        check_pair_predicates("b", &pair, &a, &b, &pair["postgis"], &mut rows);
    }
    finish("b_holes", &rows);
}

#[test]
fn family_c_antimeridian_and_poles() {
    let mut rows = Vec::new();
    for pair in load_pairs("c_antimeridian_poles") {
        let (a, b) = pair_geoms(&pair).expect("geom");
        check_pair_predicates("c", &pair, &a, &b, &pair["postgis"], &mut rows);
    }
    finish("c_antimeridian_poles", &rows);
}

#[test]
fn family_d_degenerate_inputs() {
    let mut rows = Vec::new();
    for pair in load_pairs("d_degenerate") {
        let i = pair["i"].as_u64().unwrap() as usize;
        let tag = pair["tag"].as_str().unwrap_or("").to_string();
        let ajs = js(&pair["a"]);
        let bjs = js(&pair["b"]);
        let pg = &pair["postgis"];
        let parsed = pair_geoms(&pair);
        // E4's Geom constructor does not refuse: rings are implicitly closed
        // (`core/kernel/src/spatial.rs:348`, `ring_edges` in spatial_geometry.rs).
        let (a, b) = match parsed {
            Ok(v) => v,
            Err(e) => {
                rows.push(Disagree {
                    family: "d",
                    i,
                    tag: tag.clone(),
                    pred: "e4_parse".into(),
                    a: ajs,
                    b: bjs,
                    postgis: format!("a_valid={}", pg["a_valid"]),
                    e4: format!("refuse: {e}"),
                });
                continue;
            }
        };
        let e4_behaviour = if tag == "unclosed_ring" {
            "normalise_implicit_close"
        } else {
            "accept"
        };
        eprintln!(
            "d[{i}] tag={tag} postgis_valid={} reason={} e4={e4_behaviour}",
            pg["a_valid"],
            pg["a_valid_reason"].as_str().unwrap_or(""),
        );
        let mut push = |pred: &str, e4: String, postgis: String, ok: bool| {
            if ok {
                return;
            }
            if let Some(why) = documented_deviation("d", &tag, pred, &a, &b, pg) {
                eprintln!("DOCUMENTED d[{i}] tag={tag} pred={pred} e4={e4} postgis={postgis}: {why}");
                return;
            }
            rows.push(Disagree {
                family: "d",
                i,
                tag: tag.clone(),
                pred: pred.to_string(),
                a: ajs.clone(),
                b: bjs.clone(),
                postgis,
                e4,
            });
        };
        if let Some(want) = f64_field(pg, "a_area_m2") {
            let got = area_m2(&a);
            push("area_m2", format!("{got}"), format!("{want}"), area_ok(got, want));
        }
        if let Some(want) = f64_field(pg, "a_perimeter_m") {
            let got = perimeter_m(&a);
            push(
                "perimeter_m",
                format!("{got}"),
                format!("{want}"),
                dist_ok(got, want),
            );
        }
        if let (Some(wlon), Some(wlat)) = (f64_field(pg, "a_centroid_lon"), f64_field(pg, "a_centroid_lat"))
        {
            match centroid(&a) {
                None => push(
                    "centroid",
                    "None".into(),
                    format!("[{wlon},{wlat}]"),
                    false,
                ),
                Some(got) => {
                    let gap = lonlat_gap_deg(got, (wlon, wlat));
                    push(
                        "centroid",
                        format!("[{},{}] gap_deg={gap}", got.0, got.1),
                        format!("[{wlon},{wlat}]"),
                        gap <= centroid_tol(&a),
                    );
                }
            }
        }
        if let Some(want) = bool_field(pg, "intersects") {
            let got = intersects(&a, &b);
            push("intersects", got.to_string(), want.to_string(), got == want);
        }
        if let Some(want) = bool_field(pg, "point_within_a") {
            let got = within(&b, &a);
            push("within(point,a)", got.to_string(), want.to_string(), got == want);
        }
        if let Some(want) = bool_field(pg, "a_contains_point") {
            let got = contains(&a, &b);
            push("contains", got.to_string(), want.to_string(), got == want);
        }
        if let Some(want) = f64_field(pg, "distance_m") {
            let got = distance_m(&a, &b);
            push(
                "distance_m",
                format!("{got}"),
                format!("{want}"),
                dist_ok(got, want),
            );
        }
    }
    finish("d_degenerate", &rows);
}

#[test]
fn family_e_dwithin_thresholds() {
    let mut rows = Vec::new();
    for pair in load_pairs("e_dwithin") {
        let i = pair["i"].as_u64().unwrap() as usize;
        let tag = pair["tag"].as_str().unwrap_or("").to_string();
        let ajs = js(&pair["a"]);
        let bjs = js(&pair["b"]);
        let (a, b) = pair_geoms(&pair).expect("geom");
        let pg = &pair["postgis"];
        if let Some(want) = f64_field(pg, "distance_m") {
            let got = distance_m(&a, &b);
            if !dist_ok(got, want) {
                rows.push(Disagree {
                    family: "e",
                    i,
                    tag: tag.clone(),
                    pred: "distance_m".into(),
                    a: ajs.clone(),
                    b: bjs.clone(),
                    postgis: format!("{want}"),
                    e4: format!("{got}"),
                });
            }
        }
        for entry in pg["dwithin"].as_array().cloned().unwrap_or_default() {
            let radius = entry["radius_m"].as_f64().expect("radius_m");
            let want = entry["dwithin"].as_bool().expect("dwithin");
            let got = dwithin_m(&a, &b, radius);
            if got != want {
                rows.push(Disagree {
                    family: "e",
                    i,
                    tag: tag.clone(),
                    pred: format!("dwithin@{radius}m"),
                    a: ajs.clone(),
                    b: bjs.clone(),
                    postgis: want.to_string(),
                    e4: got.to_string(),
                });
            }
        }
    }
    finish("e_dwithin", &rows);
}

#[test]
fn family_f_multipolygon_multipoint_linestring() {
    let mut rows = Vec::new();
    for pair in load_pairs("f_multi") {
        let (a, b) = pair_geoms(&pair).expect("geom");
        check_pair_predicates("f", &pair, &a, &b, &pair["postgis"], &mut rows);
    }
    finish("f_multi", &rows);
}

#[test]
fn family_g_large_and_pole_containing() {
    let mut rows = Vec::new();
    for pair in load_pairs("g_large_pole") {
        let (a, b) = pair_geoms(&pair).expect("geom");
        check_pair_predicates("g", &pair, &a, &b, &pair["postgis"], &mut rows);
    }
    finish("g_large_pole", &rows);
}

#[test]
fn family_h_area_length_perimeter_centroid() {
    let mut rows = Vec::new();
    for item in load_singles("h_measures") {
        let i = item["i"].as_u64().unwrap() as usize;
        let tag = item["tag"].as_str().unwrap_or("").to_string();
        let ajs = js(&item["g"]);
        let bjs = js(&empty_geom());
        let g = match geom_from_geojson(&item["g"]) {
            Ok(g) => g,
            Err(e) => {
                rows.push(Disagree {
                    family: "h",
                    i,
                    tag,
                    pred: "e4_parse".into(),
                    a: ajs,
                    b: bjs,
                    postgis: "parsed by PostGIS".into(),
                    e4: e,
                });
                continue;
            }
        };
        let pg = &item["postgis"];
        let mut push = |pred: &str, e4: String, postgis: String, ok: bool| {
            if ok {
                return;
            }
            if let Some(why) = documented_deviation("h", &tag, pred, &g, &g, pg) {
                eprintln!("DOCUMENTED h[{i}] tag={tag} pred={pred} e4={e4} postgis={postgis}: {why}");
                return;
            }
            rows.push(Disagree {
                family: "h",
                i,
                tag: tag.clone(),
                pred: pred.to_string(),
                a: ajs.clone(),
                b: bjs.clone(),
                postgis,
                e4,
            });
        };
        if let Some(want) = f64_field(pg, "area_m2") {
            let got = area_m2(&g);
            push("area_m2", format!("{got}"), format!("{want}"), area_ok(got, want));
        }
        if let Some(want) = f64_field(pg, "length_m") {
            let got = length_m(&g);
            push("length_m", format!("{got}"), format!("{want}"), dist_ok(got, want));
        }
        if let Some(want) = f64_field(pg, "perimeter_m") {
            let got = perimeter_m(&g);
            push(
                "perimeter_m",
                format!("{got}"),
                format!("{want}"),
                dist_ok(got, want),
            );
        }
        match (f64_field(pg, "centroid_lon"), f64_field(pg, "centroid_lat"), centroid(&g)) {
            (Some(wlon), Some(wlat), Some(got)) => {
                let gap = lonlat_gap_deg(got, (wlon, wlat));
                push(
                    "centroid",
                    format!("[{},{}] gap_deg={gap}", got.0, got.1),
                    format!("[{wlon},{wlat}]"),
                    gap <= centroid_tol(&g),
                );
            }
            (None, None, None) => {}
            (wlon, wlat, got) => {
                push(
                    "centroid",
                    format!("{got:?}"),
                    format!("{wlon:?},{wlat:?}"),
                    false,
                );
            }
        }
    }
    finish("h_measures", &rows);
}

fn gj(s: &str) -> Geom {
    geom_from_geojson(&serde_json::from_str(s).unwrap()).unwrap()
}

/// Family A a[287]: two ~100 m squares whose facing meridians are 7 cm
/// apart. Karney (`distance_m` in `src/spatial_geometry.rs`) reports
/// 0.0740903 m; this PostGIS 3.6 geography reports distance 0 and
/// `ST_Intersects` true.
///
/// DOCUMENTED, not copied. The two rings do not share a point: their facing
/// edges are meridians 7.4 cm apart, and a meridian IS its own geodesic, so
/// there is no bulge to close the gap and nothing for a spheroidal edge
/// model to find. PostGIS's 0 is a geography snap; E4 keeps the metre.
/// `documented_deviation`'s `("a", "apart_0_3m", ...)` arm lets exactly this
/// through in the family walk, and only while the gap stays under
/// `PG_GEOGRAPHY_SNAP_M`.
#[test]
fn documented_cm_meridian_gap_postgis_reports_touch() {
    let a = gj(r#"{"type":"Polygon","coordinates":[[[-46.708787179359106,-23.76554452035991],[-46.70778324624615,-23.76554452035991],[-46.70778324624615,-23.764625715343414],[-46.708787179359106,-23.764625715343414],[-46.708787179359106,-23.76554452035991]]]}"#);
    let b = gj(r#"{"type":"Polygon","coordinates":[[[-46.707782519409385,-23.76554452035991],[-46.70677858629643,-23.76554452035991],[-46.70677858629643,-23.764625715343414],[-46.707782519409385,-23.764625715343414],[-46.707782519409385,-23.76554452035991]]]}"#);
    // PostGIS: intersects true, distance 0.
    let got = distance_m(&a, &b);
    assert!(!intersects(&a, &b), "e4 keeps the two rings disjoint; got distance_m={got}");
    assert!(
        dist_ok(got, 0.074_090_300_066_460_07),
        "e4 distance_m={got}, the Karney gap between two facing meridians"
    );
    assert!(
        got > 0.0 && got <= PG_GEOGRAPHY_SNAP_M,
        "the documented snap window the family walk allows: 0 < {got} <= {PG_GEOGRAPHY_SNAP_M}"
    );
}

/// Family B on_outer_boundary: point at the arithmetic midpoint of a
/// constant-latitude north edge. PostGIS geography: intersects true,
/// distance 0. FIXED in loop 2.
///
/// The probe that settled it, on this server, for the edge below taken
/// alone as a LINESTRING geography:
///
/// ```text
/// edge as-is            0.0272779 m
/// edge 0.1 m north      0.1274830 m   (= 0.1 + 0.0273)
/// edge 0.1 m south      9.9932278 m … 10 − 0.0273 at 10 m
/// point crossing        between +2.4e-7 and +2.5e-7 deg of latitude
/// ```
///
/// So PostGIS does NOT snap: its edge is the great circle, that great circle
/// runs 2.73 cm POLEWARD of the parallel at the midpoint, and the midpoint
/// is therefore 2.73 cm INSIDE the ring. E4 said outside because
/// `ring_lens_parity` had no planar verdict to correct for a point sitting
/// exactly on the straight ring; it now answers from the point's side of
/// that edge's own great circle against the ring's winding.
#[test]
fn repro_constant_latitude_north_edge_midpoint() {
    let pt = gj(r#"{"type":"Point","coordinates":[37.5842061788395,55.84201701091608]}"#);
    let poly = gj(r#"{"type":"Polygon","coordinates":[[[37.57643279187031,55.83328687951804],[37.59197956580869,55.83328687951804],[37.59197956580869,55.84201701091608],[37.57643279187031,55.84201701091608],[37.57643279187031,55.83328687951804]],[[37.58197013074708,55.836396315352204],[37.58197013074708,55.83890757508192],[37.58644222693192,55.83890757508192],[37.58644222693192,55.836396315352204],[37.58197013074708,55.836396315352204]]]}"#);
    assert_eq!(
        intersects(&pt, &poly),
        true,
        "e4 intersects={} postgis=true; e4 distance_m={}",
        intersects(&pt, &poly),
        distance_m(&pt, &poly)
    );
    assert!(
        dist_ok(distance_m(&pt, &poly), 0.0),
        "e4 distance_m={} postgis=0",
        distance_m(&pt, &poly)
    );
}

/// Family C: point at lon 0 vs a thin antimeridian-crossing strip.
/// Intersects agrees (false). Distance disagrees at ~0.5% relative
/// (~80 km on 15 700 km) — `nearest_within` at spatial_geometry.rs:1120.
#[test]
fn repro_antimeridian_far_point_distance() {
    let a = gj(r#"{"type":"Polygon","coordinates":[[[178.78956114240634,18.682405895252447],[-178.78956114240634,18.682405895252447],[-178.78956114240634,19.430275227416555],[178.78956114240634,19.430275227416555],[178.78956114240634,18.682405895252447]]]}"#);
    let b = gj(r#"{"type":"Point","coordinates":[0.0,19.0563405613345]}"#);
    let pg = 15_744_708.608_566_8;
    let got = distance_m(&a, &b);
    assert!(
        dist_ok(got, pg),
        "e4 distance_m={got} postgis={pg} rel={}",
        (got - pg).abs() / pg
    );
}

/// Family D unclosed ring: E4 `ring_edges` adds the closing edge; PostGIS
/// `ST_IsValid` is false ("Points of LinearRing do not form a closed
/// linestring") and `ST_Area`/`ST_Perimeter` measure the open ring (area
/// ~half, perimeter 3 sides of 4).
///
/// DOCUMENTED, not copied: rings are implicitly closed by spec
/// (`core/kernel/src/spatial.rs:348`). This test asserts E4's normalisation —
/// exactly twice PostGIS's area, and the fourth side's length on top of
/// PostGIS's perimeter — so the choice stays visible and a drift in either
/// direction fails.
#[test]
fn documented_unclosed_ring_e4_closes_postgis_does_not() {
    let a = gj(r#"{"type":"Polygon","coordinates":[[[-73.6610518305111,40.47008944877067],[-73.65914914875398,40.47008944877067],[-73.65914914875398,40.47153688861146],[-73.6610518305111,40.47153688861146]]]}"#);
    // The same ring written closed: E4's normalisation is exactly this, and
    // stating it that way is stronger than a magic constant.
    let closed = gj(r#"{"type":"Polygon","coordinates":[[[-73.6610518305111,40.47008944877067],[-73.65914914875398,40.47008944877067],[-73.65914914875398,40.47153688861146],[-73.6610518305111,40.47153688861146],[-73.6610518305111,40.47008944877067]]]}"#);
    let (got_area, got_perim) = (area_m2(&a), perimeter_m(&a));
    assert!(
        area_ok(got_area, area_m2(&closed)) && dist_ok(got_perim, perimeter_m(&closed)),
        "e4 measures the unclosed ring as the closed one: area_m2={got_area} perimeter_m={got_perim}"
    );
    // PostGIS refuses validity and measures something else: half the area
    // (`ST_IsValid` false, "Points of LinearRing do not form a closed
    // linestring") and three of the four sides.
    let pg_area = 12_967.435_211_658_478;
    let pg_perim = 483.440_976_631_772_86;
    assert!(
        !area_ok(got_area, pg_area) && !dist_ok(got_perim, pg_perim),
        "the documented disagreement: e4 ({got_area} m², {got_perim} m) vs postgis ({pg_area} m², {pg_perim} m)"
    );
}

/// Family D bowtie: PostGIS `ST_Contains` of a point in a self-intersecting
/// ring is true; E4's planar PIP (`contains_point_polygon`) is false.
///
/// DOCUMENTED, not copied. `ST_IsValid` is false ("Self-intersection"), and
/// GEOS's answer on an invalid ring is an artefact of its own noding, not a
/// containment anyone specified. E4 refuses it.
#[test]
fn documented_bowtie_point_in_self_touching_ring() {
    let a = gj(r#"{"type":"Polygon","coordinates":[[[18.39351543869591,-34.17554466512626],[18.395264975403077,-34.17409722528547],[18.395264975403077,-34.17554466512626],[18.39351543869591,-34.17409722528547],[18.39351543869591,-34.17554466512626]]]}"#);
    let b = gj(r#"{"type":"Point","coordinates":[18.39460889913789,-34.17464001522577]}"#);
    assert!(!contains(&a, &b), "e4 refuses containment in a bowtie; postgis/GEOS says true");
    assert!(!within(&b, &a), "the same, the other way round");
}

/// Family G polar triangle: vertices at one parallel, 120° apart. PostGIS
/// geography contains the pole and a point between the parallel and the pole.
/// E4 `point_in_ring_geodesic` (spatial_geometry.rs:873) ray-casts the
/// planar triangle (which does not contain the pole) and `ring_lens_parity`
/// (line 820) does not flip it.
#[test]
fn repro_polar_triangle_contains_pole() {
    let a = gj(r#"{"type":"Polygon","coordinates":[[[0.0,71.27727037780164],[120.0,71.27727037780164],[-120.0,71.27727037780164],[0.0,71.27727037780164]]]}"#);
    let b = gj(r#"{"type":"Point","coordinates":[0.0,90.0]}"#);
    assert_eq!(
        intersects(&a, &b),
        true,
        "e4 intersects={} postgis=true; e4 distance_m={}",
        intersects(&a, &b),
        distance_m(&a, &b)
    );
}

/// Family G: a 117°×35° lon/lat rectangle vs a small square in its planar
/// interior. PostGIS geography: disjoint, 25 km; E4 `geodesic_overlap`
/// (spatial_geometry.rs:1028) reports overlap. Geodesic south-edge bulge on
/// a >90° span is far past the 50K-corpus millimetre/metre band.
#[test]
fn repro_large_span_geodesic_interior() {
    let a = gj(r#"{"type":"Polygon","coordinates":[[[22.78819591825288,29.503844920576796],[140.2671822376068,29.503844920576796],[140.2671822376068,64.0880147845103],[22.78819591825288,64.0880147845103],[22.78819591825288,29.503844920576796]]]}"#);
    let b = gj(r#"{"type":"Polygon","coordinates":[[[80.86697379197149,46.3436049022993],[82.18840436388818,46.3436049022993],[82.18840436388818,47.248254802787805],[80.86697379197149,47.248254802787805],[80.86697379197149,46.3436049022993]]]}"#);
    assert_eq!(
        intersects(&a, &b),
        false,
        "e4 intersects={} postgis=false; e4 distance_m={} postgis=25246.58",
        intersects(&a, &b),
        distance_m(&a, &b)
    );
}

/// Family G: GeoJSON rectangle lon -180..180, lat cap..90. PostGIS
/// geography collapses ±180 to one meridian, so the ring is a polar sliver
/// and a point at (0, 90) / (0, 89.999) is not in the interior the same way
/// E4's planar-lon PIP (`point_in_ring_geodesic` ray-cast at
/// spatial_geometry.rs:884) reads a full-world rectangle.
#[test]
fn repro_dateline_polar_rectangle() {
    let a = gj(r#"{"type":"Polygon","coordinates":[[[-180.0,71.13777539468444],[180.0,71.13777539468444],[180.0,90.0],[-180.0,90.0],[-180.0,71.13777539468444]]]}"#);
    let b = gj(r#"{"type":"Point","coordinates":[0.0,89.999]}"#);
    // PostGIS 3.6 geography: ±180 is one meridian, so this ring is a polar
    // sliver; (0, 89.999) is ~111 m from the collapsed north-edge/pole and
    // ST_Intersects is false. E4 ray-casts a full-world rectangle.
    assert_eq!(
        intersects(&a, &b),
        false,
        "e4 intersects={} postgis=false; e4 distance_m={} postgis=111.69",
        intersects(&a, &b),
        distance_m(&a, &b)
    );
}

/// Documented areal-centroid gap (`tests/spatial_geometry_postgis.rs`,
/// `mpoly_with_hole`, ~0.48 deg). Named so it stays visible rather than
/// being folded into a family count. E4 is not patched.
#[test]
fn documented_hole_centroid_gap() {
    let item = load_singles("h_measures")
        .into_iter()
        .find(|s| s["tag"] == "mpoly_with_hole_documented")
        .expect("documented hole case");
    let g = geom_from_geojson(&item["g"]).unwrap();
    let want = (
        item["postgis"]["centroid_lon"].as_f64().unwrap(),
        item["postgis"]["centroid_lat"].as_f64().unwrap(),
    );
    let got = centroid(&g).expect("centroid defined");
    let gap = lonlat_gap_deg(got, want);
    eprintln!(
        "hole-centroid gap: e4=({:.6},{:.6}) postgis=({:.6},{:.6}) gap={gap:.6} deg (documented ~0.48)",
        got.0, got.1, want.0, want.1
    );
    // DOCUMENTED, not copied. `polygon_planar_centroid` is a planar shoelace
    // with holes subtracted as `outer·|Ao| − hole·|Ah|`; PostGIS's geography
    // centroid is spherical and is not that algebra. Re-querying with the
    // hole ring reversed gives PostGIS the identical centroid, so this is not
    // a winding artefact (`tests/spatial_geometry_postgis.rs`). The assertion
    // pins the gap at the value the owner has seen, so it cannot drift
    // unnoticed in either direction.
    assert!(
        (gap - 0.477_678).abs() < 1e-3,
        "documented hole-centroid gap: e4={got:?} postgis={want:?} gap={gap} deg (documented 0.4777)"
    );
}




/// The midpoints of a ring's four constant-coordinate edges, all four ways,
/// against this PostGIS 3.6 server. The ring is family B's `on_outer_boundary`
/// outer ring; the probes are `ST_Intersects`/`ST_Distance` of each midpoint
/// against it as a geography.
///
/// ```text
/// north-edge midpoint   true, 0          (2.73 cm INSIDE: the geodesic bulges out)
/// south-edge midpoint   false, 0.0272812 (2.73 cm OUTSIDE: the geodesic bulges in)
/// west-edge midpoint    true, 0          (a meridian IS its own geodesic)
/// ring vertex           true, 0
/// ```
///
/// One rule produces all four: a point exactly on a straight chord is inside
/// the geography ring iff it is on the ring's interior side of that edge's
/// own great circle. North and south are opposite signs of the same
/// centimetre, which is why a fix that only knew about "north edges" would
/// have been wrong half the time — and why
/// `tests/spatial_geometry_postgis.rs` (a south edge, PostGIS 3.4, 1.2 cm)
/// and this file (a north edge, PostGIS 3.6, 2.7 cm) now agree.
#[test]
fn documented_constant_latitude_edge_midpoints() {
    let ring = r#"{"type":"Polygon","coordinates":[[[37.57643279187031,55.83328687951804],[37.59197956580869,55.83328687951804],[37.59197956580869,55.84201701091608],[37.57643279187031,55.84201701091608],[37.57643279187031,55.83328687951804]]]}"#;
    let r = gj(ring);
    let pt = |lon: f64, lat: f64| Geom::Point(lon, lat);

    let north_mid = pt(37.5842061788395, 55.84201701091608);
    assert!(intersects(&north_mid, &r), "north-edge midpoint is inside (postgis true)");
    assert!(dist_ok(distance_m(&north_mid, &r), 0.0), "postgis 0");

    let south_mid = pt(37.5842061788395, 55.83328687951804);
    assert!(!intersects(&south_mid, &r), "south-edge midpoint is outside (postgis false)");
    assert!(
        dist_ok(distance_m(&south_mid, &r), 0.02728116),
        "e4 distance_m={} postgis=0.02728116",
        distance_m(&south_mid, &r)
    );

    let west_mid = pt(37.57643279187031, 55.83765194521706);
    assert!(intersects(&west_mid, &r), "a meridian edge has no bulge (postgis true)");
    assert!(dist_ok(distance_m(&west_mid, &r), 0.0), "postgis 0");

    let vertex = pt(37.57643279187031, 55.83328687951804);
    assert!(intersects(&vertex, &r), "a ring vertex is on the boundary (postgis true)");
    assert!(dist_ok(distance_m(&vertex, &r), 0.0), "postgis 0");
}

/// A `geography` edge is the GREAT CIRCLE through its two vertices — with
/// `(lon, lat)` read straight onto a sphere — and NOT the WGS84 geodesic.
/// Only the distances between points are spheroidal. This is the fact
/// `point_to_segment_geodesic_m` is built on, and it is worth an assertion
/// because the two models part by kilometres once an edge is wide.
///
/// Family G's 117.48°-wide south edge at latitude 29.503844920576796, probed
/// on this server:
///
/// ```sql
/// SELECT ST_AsText(ST_ClosestPoint(edge::geography, corner::geography));
/// -- POINT(80.86411847825508 47.475329257577954)
/// SELECT ST_Distance(edge::geography, corner::geography);
/// -- 25246.58142148
/// ```
///
/// `atan(tan(29.503844920576796°) / cos(117.48°/2))` = 47.475329°, the great
/// circle's own maximum latitude, to eight figures. The WGS84 geodesic
/// between the same two vertices tops out at 47.566990° instead — 10.2 km
/// further north — and interpolating along IT moves this answer to
/// 35,223.56 m, a 39% error against the server.
#[test]
fn documented_postgis_edges_are_great_circles() {
    let edge = gj(r#"{"type":"LineString","coordinates":[[22.78819591825288,29.503844920576796],[140.2671822376068,29.503844920576796]]}"#);
    let corner = Geom::Point(80.86697379197149, 47.248254802787805);
    let got = distance_m(&edge, &corner);
    assert!(
        dist_ok(got, 25_246.581_421_48),
        "e4 distance_m={got} postgis=25246.58142148 (great-circle edge); \
         the WGS84-geodesic edge would give 35223.56"
    );
    // And the closest point PostGIS names is ON that great circle, to
    // fourteen decimal places of a degree. For a great circle with maximum
    // latitude `φm` at longitude `λm`, `tan φ(λ) = tan φm · cos(λ − λm)`,
    // with `tan φm = tan φ / cos(Δλ/2)` from the two same-latitude vertices.
    let (lat, lon_a, lon_b) = (
        29.503_844_920_576_796f64,
        22.788_195_918_252_88f64,
        140.267_182_237_606_8f64,
    );
    let (span, lon_mid) = (lon_b - lon_a, (lon_a + lon_b) / 2.0);
    let tan_max = lat.to_radians().tan() / (span / 2.0).to_radians().cos();
    let closest_lon = 80.864_118_478_255_08f64;
    let on_circle = (tan_max * (closest_lon - lon_mid).to_radians().cos())
        .atan()
        .to_degrees();
    assert!(
        (on_circle - 47.475_329_257_577_954).abs() < 1e-9,
        "great circle at lon {closest_lon}: {on_circle}; ST_ClosestPoint 47.475329257577954"
    );
}

/// Family D `zero_area`: a collapsed spike ring `[v0, v1, v0, v2, v0]`.
/// `ST_IsValid` is false ("Self-intersection"), and PostGIS's polygon and
/// boundary distance both drop the spike edge:
///
/// ```text
/// ST_Distance(point, east_edge  AS LINESTRING)  20.03783178   <- E4's answer
/// ST_Distance(point, north_edge AS LINESTRING)  20.15165579
/// ST_Distance(point, ST_Boundary(polygon))      20.15165579
/// ST_Distance(point, polygon)                   20.15165579
/// ```
///
/// DOCUMENTED, not copied, and the same class as the bowtie: E4 measures
/// every edge the ring names, and PostGIS itself agrees with E4's number the
/// moment that edge is handed to it as a valid geometry.
#[test]
fn documented_collapsed_spike_ring_distance() {
    let a = gj(r#"{"type":"Polygon","coordinates":[[[-46.85454020930724,-23.345868217802025],[-46.853751954520135,-23.345868217802025],[-46.85454020930724,-23.345868217802025],[-46.85454020930724,-23.345144497881634],[-46.85454020930724,-23.345868217802025]]]}"#);
    let b = Geom::Point(-46.854343145610464, -23.345687287821928);
    let got = distance_m(&a, &b);
    assert!(
        dist_ok(got, 20.037_831_78),
        "e4 distance_m={got}; postgis for that same edge as a LINESTRING is 20.03783178, \
         and 20.15165579 for the invalid polygon"
    );
}
